### ISSUE TITLE
All Assistants getting exceptions during analysis after refactor

### ISSUE THREAD

**Issue by rreganjr** [rreganjr/Requel#17]
```
2018-06-13 01:30:36.153 ERROR 37348 --- [ taskExecutor-1] r.r.p.i.a.ProjectOrDomainEntityAssistant : failed to add note indicating failure of glossary term identification for the Name of interface com.rreganjr.requel.project.Actor[48]:System Admin

com.rreganjr.EntityException: The unknown conflicts with an existing <unknown>
	at com.rreganjr.EntityException.uniquenessConflict(EntityException.java:120) ~[classes/:na]
	at com.rreganjr.repository.jpa.ConstraintViolationExceptionAdapter.convert(ConstraintViolationExceptionAdapter.java:63) ~[classes/:na]
	at com.rreganjr.repository.ExceptionMapper.convertException(ExceptionMapper.java:157) ~[classes/:na]
	at com.rreganjr.repository.ExceptionMapper.convertException(ExceptionMapper.java:110) ~[classes/:na]
	at com.rreganjr.repository.ExceptionMappingCommandHandler.execute(ExceptionMappingCommandHandler.java:52) ~[classes/:na]
	at com.rreganjr.repository.RetryOnLockFailuresCommandHandler.execute(RetryOnLockFailuresCommandHandler.java:67) ~[classes/:na]
	at com.rreganjr.requel.project.impl.assistant.AbstractAssistant.addNote(AbstractAssistant.java:87) ~[classes/:na]
	at com.rreganjr.requel.project.impl.assistant.ProjectOrDomainEntityAssistant.analyzeProperty(ProjectOrDomainEntityAssistant.java:202) [classes/:na]
	at com.rreganjr.requel.project.impl.assistant.ProjectOrDomainEntityAssistant.analyze(ProjectOrDomainEntityAssistant.java:123) [classes/:na]
	at com.rreganjr.requel.project.impl.assistant.TextEntityAssistant.analyze(TextEntityAssistant.java:72) [classes/:na]
	at com.rreganjr.requel.project.impl.assistant.UseCaseAssistant.analyze(UseCaseAssistant.java:66) [classes/:na]
	at com.rreganjr.requel.project.impl.assistant.ProjectAssistant.analyzeUseCases(ProjectAssistant.java:119) [classes/:na]
	at com.rreganjr.requel.project.impl.assistant.ProjectAssistant.analyze(ProjectAssistant.java:71) [classes/:na]
	at com.rreganjr.requel.project.impl.assistant.AssistantFacade$1.run(AssistantFacade.java:186) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by rreganjr** [comment]
branch 1.0.3

new module annotatable-mapping to hold named @AnyMetaDef name = "annotatables" that references the requel-project module so that project entities can be MetaValue mapped to the annotatables collection on AbstractAnnotation without a circular dependency between annotation and project modules. Not sure this is working as I had a lot of cyclic dependencies via the iml files, although some of the references seemed suspect and I did some manual cleanup.

**Comment by rreganjr** [comment]
I imported the Requel project and no more analyzer errors.
